### ISSUE TITLE
RefreshControl Support

### ISSUE THREAD

**Issue by ssssssssssss** [Flipkart/ReactEssentials#39]
From the documents, it looks like there is no RefreshControl support yet. Do you consider this lib as a drop in replacement of FlatList in the future?
Thanks.

**Comment by naqvitalha** [comment]
This component is written on top of ScrollView which already comes with Refresh Control. Cannot be a 100% drop in replacement since we require LayoutProvider and item types to make necessary assumptions. It is not optional. Both libraries are, however, very similar in terms of contracts.
Close the issue if it answers your question.
