### ISSUE TITLE
Calling 'scrollToIndex' while manually scrolling causes blank content

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/ReactEssentials#45]
I have a specific case here where there's a button that scrolls to a specific index in the list. If I tap the button when the list is idle, it scrolls there and renders things just fine, but if the user is already scrolling in the list, it scrolls to its destination and shows blank content until I start scrolling again.

As far as I understood from the source code, there's a render stack that's prepared and it's being updated on scroll. The problem is that as the user is scrolling, if I force the list to go to a specific index with no animation, the renderStack loses track of the items it should render, until I start scrolling again, and then the renderStack gets updated and it renders things correctly again.

I hope my explanation made sense. Please let me know if I need to elaborate further.

**Comment by naqvitalha** [comment]
@AbdallaMohamed when you scroll with no Animation can you check if onScroll of scrollView or RecyclerListView is fired? I remember opening this issue on RN https://github.com/facebook/react-native/issues/15563 . They closed it though, the problem was that onScroll on Android would not fire at all in some cases. Check if this is the same issue. Also, I assume you're trying on Android, if yes, try on iOS it should be fine. You might want to raise a new issue on RN if I'm right. Whatever we do here will be a workaround.

**Comment by AbdallaMohamed** [comment]
It's happening on iOS as well. Looks like it's a thing in react-native itself. I did a workaround by scrolling to the previous day first without animation and then scrolling to the destination day with animation. This will refresh the render stack and eliminate blank content.

```
this._recyclerListView.scrollToIndex(dayIndex - 1, false);
this._recyclerListView.scrollToIndex(dayIndex, true);
```

I'll close the issue for now. Thanks for the quick reply though!
